language: objective-c
notifications:
  email: true

script:
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO

branches:
 only:
 - master
 
xcode_project: ExpandableTextView.xcodeproj
xcode_scheme: ExpandableTextView
